import os
import numpy as np
import pickle
from tqdm import tqdm
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score, matthews_corrcoef

from omniphish.dataset_loader import PhishingDataset
import random
import torch

def set_seed(seed=42):
    """Locks all random seeds for exact reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)

set_seed(42)

def load_and_extract_tfidf():
    """
    Loads the dataset and uses TF-IDF vectorization to convert raw HTML
    into mathematical word-frequency vectors, representing a traditional NLP SOTA.
    """
    dirs = {
        'phishing': 'dataset/raw_html/phishing',
        'benign': 'dataset/raw_html/benign'
    }
    
    dataset = PhishingDataset(dirs, undersample_benign=False)
    dataset_len = len(dataset)
    
    if dataset_len == 0:
        print("Dataset is empty. Run phish_scraper.py first.")
        return None, None, None, None, None
        
    print(f"\n[+] Extracting Raw HTML Text from {dataset_len} files for TF-IDF...")
    all_texts = []
    all_labels = []
    
    for i in tqdm(range(dataset_len), desc="Loading HTML"):
        filepath = dataset.samples[i]
        label = dataset.labels[i]
        
        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                raw_html = f.read()
            all_texts.append(raw_html)
            all_labels.append(label)
        except Exception:
            all_texts.append("")
            all_labels.append(label)
            
    print("\n[+] Vectorizing HTML using TF-IDF (Max Features: 10,000)...")
    # TF-IDF extracts the top 10,000 most mathematically significant tokens/words
    vectorizer = TfidfVectorizer(max_features=10000, stop_words='english')
    X_tfidf = vectorizer.fit_transform(all_texts)
    all_labels = np.array(all_labels)
    
    # --- ZERO-DAY VAULT ISOLATION ---
    indices = np.arange(dataset_len)
    
    if os.path.exists("weights/vault_indices.npy"):
        print("[+] Loading exact Zero-Day Vault indices generated by Deep Learning trainer...")
        test_idx = np.load("weights/vault_indices.npy")
        train_val_idx = np.setdiff1d(indices, test_idx)
    else:
        print("[!] No vault_indices.npy found. Falling back to random 10% split.")
        from sklearn.model_selection import train_test_split
        train_val_idx, test_idx = train_test_split(indices, test_size=0.1, stratify=all_labels, random_state=42)
    
    X_train = X_tfidf[train_val_idx]
    y_train = all_labels[train_val_idx]
    
    X_test = X_tfidf[test_idx]
    y_test = all_labels[test_idx]
    
    return X_train, y_train, X_test, y_test, vectorizer

def train_sota():
    print("="*50)
    print("🚀 SOTA MODEL: TF-IDF + Logistic Regression")
    print("="*50)
    
    X_train, y_train, X_test, y_test, vectorizer = load_and_extract_tfidf()
    if X_train is None:
        return
        
    print(f"\n[+] Training Cost-Sensitive Logistic Regression on {X_train.shape[0]} samples...")
    # Logistic Regression is highly optimized for high-dimensional sparse TF-IDF matrices
    lr_model = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)
    lr_model.fit(X_train, y_train)
    
    os.makedirs("weights", exist_ok=True)
    with open("weights/sota_tfidf_lr.pkl", "wb") as f:
        pickle.dump((vectorizer, lr_model), f)
    print("[+] Model and Vectorizer saved to weights/sota_tfidf_lr.pkl")
    
    # ---------------------------------------------------------
    # FINAL TESTING PHASE (IEEE METRICS)
    # ---------------------------------------------------------
    print("\n" + "="*50)
    print("🚀 RUNNING FINAL METRICS ON EXACT ZERO-DAY VAULT (10%)")
    print("="*50)
    
    all_preds = lr_model.predict(X_test)
    y_probs = lr_model.predict_proba(X_test)[:, 1]
    
    acc = accuracy_score(y_test, all_preds)
    prec = precision_score(y_test, all_preds, zero_division=0)
    rec = recall_score(y_test, all_preds, zero_division=0)
    f1 = f1_score(y_test, all_preds, zero_division=0)
    cm = confusion_matrix(y_test, all_preds)
    
    auc = roc_auc_score(y_test, y_probs)
    mcc = matthews_corrcoef(y_test, all_preds)
    tn, fp, fn, tp = cm.ravel()
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0
    
    print(f"Accuracy:  {acc*100:.2f}%")
    print(f"Precision: {prec*100:.2f}%")
    print(f"Recall:    {rec*100:.2f}%")
    print(f"F1-Score:  {f1*100:.2f}%")
    print(f"ROC-AUC:   {auc:.4f}")
    print(f"MCC:       {mcc:.4f}")
    print(f"FPR (False Positive Rate): {fpr*100:.2f}%")
    print("\nConfusion Matrix:")
    print(f"True Negatives (Correctly Safe):   {cm[0][0]}")
    print(f"False Positives (Mistake blocked): {cm[0][1]}")
    print(f"False Negatives (Missed Phish):    {cm[1][0]}")
    print(f"True Positives (Caught Phish):     {cm[1][1]}")
    print("="*50 + "\n")
    
if __name__ == "__main__":
    train_sota()
